services:
  - docker

jobs:
  include:
    # TODO: build docker image
    - stage: Integration Tests

      before_script:
        - sh cluster/setup-kind-cluster.sh
        - kubectl get node --selector=node-role.kubernetes.io/master -o json

      script:
        # Deploy app
        - sh cluster/deploy.sh
        - kubectl get deploy hello-deploy -o json

        # Expose app
        - sh cluster/expose.sh
        - kubectl get service hello-svc -o json

        # Verify app output
        - sh cluster/test.sh
