services:
  - docker

jobs:
  include:
    # TODO: build docker image
    - stage: Integration Tests

      before_script:
        - sh infra/setup-kind-cluster.sh
        - kubectl get node --selector=node-role.kubernetes.io/master -o json

      script:
        - cd src
        - sh build.sh
        - sh test.sh

      script:
        - cd infra

        # Deploy app
        - sh deploy.sh
        - kubectl get deploy hello-deploy -o json

        # Expose app
        - sh expose.sh
        - kubectl get service hello-svc -o json

        # Verify app output
        - sh test.sh
